### ISSUE TITLE
Build configuration

### ISSUE THREAD

**Issue by marcinMarcin** [marsiancba/jWorship#1]
Hey, could you add build configuration (like Maven POM) or instruction how to build your project?

Thanks,
Marcin

**Comment by marsiancba** [comment]
It is a pure java project, so just compile what is in src directory. There
were some attempts to add video playback functionality using various
libraries and there may be some traces of it in the source code, but it
should work even without presence of those libraries. Just ignore those
compile errors.

**Comment by marcinMarcin** [comment]
OK, thanks. I've just compiled it using maven.
