### ISSUE TITLE
Vyvoj

### ISSUE THREAD

**Issue by mistvan** [marsiancba/jWorship#6]
Zdravim, pracuje niekto aktivne na tomto projekte?

**Comment by marsiancba** [comment]
Pokial viem tak nie. Ale aplikacia je stale aktivne pouzivana.

**Comment by mistvan** [comment]
Mozem si spravit fork a pripadne pokracovat vo vyvoji s vasim dovolenim?

**Comment by marsiancba** [comment]
Jasne 😉

**Comment by mistvan** [comment]
Ďakujem

**Comment by marsiancba** [comment]
etse jedna dolezita poznamka: najnovsia verzia je v branch javafx a nie v master.
tu verziu aj aktualne u nas pouzivame, takze pokracovat by si mal odtial.
p.
